[book]
authors = ["Yehuda Katz"]
multilingual = false
src = "src"
title = "CrossCheck"

[output.html]
additional-css = ["theme/theme.css"]

[output.html.playpen]
editable = true

[build]
build-dir = "../docs"
